.github/workflows/nodejs.yml
----
#
Add github action support, run lint, test and build for every push and pr.
Yes.
No.
Noting.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/5)
=> Add: nodejs.yml for github actions

src/lang/zh.js, src/pages/Solution/action.js, src/pages/Solution/editsolution.js, src/pages/Solution/mysolution.js, src/pages/Solution/success.js, src/pages/Solution/viewsolution.js, src/route/router.js, webpack.dev.config.js
optimize submission page
feature
no
no
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/6)
=> submission page optimize

.github/workflows/nodejs.yml, .kodiak.toml, .travis.yml, README.md, jest.config.js, now.json
----
#
Adding CI support.
Yes
No
Nothing
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/7)
=> Add: github action, travis-ci, codeclimate, zeit/now, kodiak

package.json, src/lang/zh.js, src/pages/Bounty/action.js, src/pages/Bounty/editbounty.js, src/pages/Bounty/reducer.js, src/pages/Solution/action.js, src/pages/Solution/editsolution.js, src/pages/Solution/reducer.js, src/utils/index.js, webpack.config.js, yarn.lock
bugfix
no
remove create bounty/submission licence confirm
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/8)
=> bugfix submit tips

.travis.yml, Jenkinsfile
----
#
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/13)
=> Add: jenkins pipeline config

Jenkinsfile
----
#
build related changes
No
No
Nothing
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/15)
=> Fix: there's no frontend test machine anymore

src/lang/zh.js, src/pages/Bounty/action.js, src/pages/Bounty/viewbounty.js, src/pages/Solution/action.js, src/pages/Solution/viewsolution.js, src/utils/index.js
fix edit bounty textarea not resize
bugfix
no
no
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/14)
=> Bugfix edit bounty TextArea element not resize

Jenkinsfile, webpack.config.js
----
#
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/17)
=> Test: debug ALI_OSS_KEYS

Jenkinsfile
Use jenkins file credential
----
#
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/19)
=> Fix: ALI_OSS_KEYS env

Jenkinsfile, webpack.config.js
Use jenkins file credential
No
No
Nothing
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/20)
=> fix oss key

src/components/Nickname/index.js, src/lang/zh.js, src/utils/api.js, src/utils/index.js
https://github.com/Conflux-Dev/bounty-server/pull/60
The feature won't work until both PRs are merged.
----
#
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/26)
=> Add: validate nickname

src/components/Nickname/index.js, src/lang/zh.js, src/utils/index.js
----
#
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/27)
=> Add: restrict nickname length

src/lang/zh.js
add two catetory
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/28)
=> add two catetory

src/App.js, src/components/BountyDeletedWarning/index.js, src/components/DailyCheckin/index.js, src/components/PageHead/action.js, src/components/PageHead/index.js, src/components/PageHead/reducer.js, src/lang/zh.js, src/pages/Bounty/commonStyle.js, src/pages/Bounty/mybounty.js, src/pages/Solution/mysolution.js, src/pages/UserInfo/my-likes.js, src/pages/UserInfo/withdraw.js
global site feature
feature
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/33)
=> global site

src/lang/zh.js, src/pages/Solution/action.js
bugfix number check
bugfix
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/34)
=> fix number check

src/lang/zh.js, src/pages/UserInfo/inviteFriends.js
----
#
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/35)
=> Add: permanent invitation code feature

oss-utils/index.js, package.json, src/components/DailyCheckin/action.js, src/components/DailyCheckin/index.js, src/pages/UserInfo/index.js, src/utils/index.js, yarn.lock
update deps and bugfix
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/36)
=> deps update & bugfix

src/lang/zh.js, src/pages/Solution/viewsolution.js, src/pages/UserInfo/index.js
bugfix
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/40)
=> 0822dev bugfix

src/components/DailyCheckin/index.js, src/lang/en.js, src/lang/zh.js
fix checkin counter
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/41)
=> fix checkin counter

src/pages/Home/index.js
bugfix
No
No
Nothing
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/43)
=> fix autoplay speed

src/pages/Home/action.js, src/pages/Home/index.js, src/pages/Home/reducer.js
bugfix
No
No
Nothing
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/45)
=> bounty list sort fix

src/pages/Bounty/viewbounty.js, src/pages/Solution/viewsolution.js
bugfix i18n
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/46)
=> bugfix i18n

src/pages/Bounty/mybounty.js, src/pages/UserInfo/my-likes.js, src/utils/index.js
add createdSiteLang
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/47)
=> add createdSiteLang

src/pages/Solution/viewsolution.js, src/pages/UserInfo/account-history.js
add query translated
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/48)
=> add query translated

src/pages/Solution/mysolution.js
fix update progress link
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/50)
=> fix update progress link

src/pages/Bounty/mybounty.js, src/pages/Solution/mysolution.js, src/pages/UserInfo/account-history.js, src/pages/UserInfo/my-likes.js
transDeleted prevent click
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/51)
=> transDeleted prevent click

src/globalStyles/base.less
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/52)
=> add disabled style

src/components/PageHead/index.js, src/components/PageHead/reducer.js, src/utils/index.js
fix default lang choose
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/55)
=> fix default lang choose

src/components/HomeBounty/index.js
bugfix
No
No
Nothing
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/58)
=> home bounty font size

src/pages/Solution/viewsolution.js
fix descriptionTranslated typo
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/61)
=> fix descriptionTranslated typo

src/components/HomeBounty/index.js
bugfix
No
No
Nothing
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/60)
=> Home feature

src/utils/index.js
allow href target
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/62)
=> allow href target

src/components/PhotoImg/index.js, src/pages/Bounty/viewbounty.js, src/pages/Solution/viewsolution.js, src/pages/UserInfo/index.js
fix set backgroundImg & fix solution order show
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/64)
=> fix set backgroundImg & fix solution order show

src/pages/Solution/viewsolution.js
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/66)
=> fix click left|right btn

src/pages/UserInfo/index.js
----
#
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/68)
=> Fix: user info avatar url

package.json, src/components/DailyCheckin/action.js, src/components/DailyCheckin/index.js, src/constants.js, src/index.js, src/pages/SignIn/index.js, src/pages/Solution/mysolution.js, src/utils/index.js, yarn.lock
Checkin recaptcha
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/71)
=> Checkin recaptcha

package.json, src/App.js, src/components/Input/index.js, src/components/PageHead/index.js, src/components/Select/index.js, src/components/Toast/ToastMessage.js, src/index.js, src/pages/Bounty/editbounty.js, src/pages/Faq/index.js, src/pages/Solution/editsolution.js, src/utils/i18n.js, src/utils/index.js, yarn.lock
update react i18n , fix faq
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/70)
=> update react i18n

src/pages/Bounty/mybounty.js, src/pages/Bounty/viewbounty.js, src/pages/Solution/mysolution.js, src/pages/UserInfo/account-history.js, src/pages/UserInfo/my-likes.js
changeToCreatedAt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/76)
=> changeToCreatedAt

src/components/DailyCheckin/index.js, src/components/ReCAPTCHA/index.js, src/constants.js, src/lang/zh.js, src/pages/SignIn/index.js, src/pages/SignUp/index.js, src/pages/Solution/mysolution.js
add Recaptha , token needs update
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/39)
=> add Recaptha

src/components/Email/index.js, src/lang/zh.js, src/pages/Bounty/commonStyle.js, src/pages/SignIn/index.js, src/pages/SignUp/index.js, src/pages/UserInfo/action.js, src/pages/UserInfo/index.js
validate recaptcha empty
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/78)
=> validate recaptcha empty

package.json, src/index.js, src/lang/zh.js, src/pages/404.js, src/pages/UserInfo/index.js, src/utils/i18n.js, webpack.config.js, yarn.lock
temp remove react-intl deps
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/82)
=> Bugfix intl

src/pages/Bounty/editbounty.js
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/88)
=> change float order

.eslintrc, .stylelintignore, package.json, src/components/HomeBounty/index.js, src/pages/404.js, src/pages/Bounty/viewbounty.js, src/pages/Solution/viewsolution.js, src/pages/UserInfo/messages.js, yarn.lock
----
#
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/89)
=> Fix: message mark all as read, update packages, fix eslint error

src/constants.js, src/pages/Bounty/action.js, src/pages/Bounty/editbounty.js, src/pages/Solution/action.js, src/pages/Solution/editsolution.js, src/pages/Solution/updateProgress.js
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/91)
=> attachment check & allow multiple uploads

src/constants.js
mobile browser not add upload accept
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/93)
=> mobile change upload accept

src/pages/UserInfo/account-history.js
bugfix
no
no
nothing
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/94)
=> fix url error

src/lang/zh.js, src/pages/UserInfo/my-likes.js, src/pages/UserInfo/settings.js
----
#
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/98)
=> Fix: product notice trans, like height in my likes, truncate email

src/components/DailyCheckin/index.js
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/100)
=> fix checkin modal style

src/pages/Solution/viewsolution.js
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/103)
=> fix submission view style bug

src/components/HomeBounty/index.js, webpack.dev.config.js
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/104)
=> fix card test disaplay

src/pages/Bounty/commonStyle.js
----
#
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/107)
=> Fix: userinfo list style

src/pages/Home/index.js
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/108)
=> fix home page no broadcastList

src/pages/SignUp/index.js
----
#
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/112)
=> Add: thirdparty no email verification code

src/components/Email/index.js, src/components/Nickname/index.js, src/pages/SignUp/index.js
1. replace space with underscore in nickname input
2. disable email input when signup through google
----
#
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/113)
=> Add: third party signup enhancement

src/App.js, src/components/DailyCheckin/action.js, src/components/DailyCheckin/index.js, src/constants.js, src/pages/Bounty/viewbounty.js, src/pages/Home/index.js
checkin status change
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/114)
=> checkin status change

src/lang/zh.js, src/utils/index.js
----
#
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/116)
=> Fix: invitation code threshold description

src/components/DailyCheckin/index.js
fix iphone screen slash
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/118)
=> fix iphone screen slash

src/pages/Home/index.js
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/123)
=> fix autoplay

renovate.json
----
#
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/124)
=> Add: remove renovate

src/pages/Bounty/viewbounty.js
use submissionIdMaxReward as max reward check
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/126)
=> use submissionIdMaxReward as max reward check

src/pages/Solution/action.js, src/pages/Solution/reducer.js, src/pages/Solution/viewsolution.js, src/utils/api.js
change to Nearby submission api
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/127)
=> change to Nearby submission api

src/pages/Bounty/viewbounty.js
bugfix
No
No
Nothing
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/130)
=> fix submission list style

src/pages/Bounty/viewbounty.js
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/131)
=> fix clear data before mount

src/pages/Bounty/viewbounty.js
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/132)
=> fix clear state in unmount

src/components/DailyCheckin/action.js
getAccout after checkin success fix
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/133)
=> getAccout after checkin success fix

src/pages/Home/index.js
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/134)
=> fix popBountyList=1 style

src/lang/zh.js, src/pages/Bounty/viewbounty.js, src/pages/Solution/viewsolution.js, src/pages/UserInfo/action.js, src/pages/UserInfo/withdraw.js
fix wordbreak style
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/135)
=> fix withdraw

src/components/Email/index.js, src/lang/zh.js, src/pages/ResetPassword/index.js
----
#
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/136)
=> Fix: tell user to signup with google if signup process is unfinished

src/components/Email/index.js
----
#
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/137)
=> Fix: put notification at wrong place

src/constants.js, src/lang/zh.js, src/pages/Solution/commonStyle.js
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/138)
=> common err msg update

src/lang/zh.js, src/pages/UserInfo/withdraw.js
The Input of the To Address is limited to a combination of letters and numbers
yes
no
nothing
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/140)
=> change toaddress

src/components/Email/index.js
Correct the word “Invalid”
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/142)
=> change invalid

src/components/Email/index.js, src/components/EmailCode/index.js, src/pages/ResetPassword/index.js, src/pages/SignIn/index.js, src/pages/SignUp/index.js, src/pages/UserInfo/settings.js
----
#
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/143)
=> Fix: email n email send, signup signin resetpwd change email

src/pages/UserInfo/withdraw.js
revert withdraw check
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/145)
=> revert withdraw check

src/pages/UserInfo/action.js, src/pages/UserInfo/withdraw.js
----
#
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/147)
=> Fix: withdraw send button style

src/pages/UserInfo/action.js, src/pages/UserInfo/withdraw.js
----
#
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/148)
=> fix send button style

src/lang/zh.js, src/pages/UserInfo/settings.js, src/utils/api.js
change "Invalid password" to "Incorrect current password" 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/150)
=> change setting.js/password

src/pages/UserInfo/action.js, src/pages/UserInfo/withdraw.js
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/151)
=> fix change password error message

src/lang/zh.js, src/pages/UserInfo/account-history.js
add type activity reward
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/152)
=> add type activity reward

src/lang/zh.js, src/pages/UserInfo/account-history.js
add Community Reward
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/154)
=> add Community Reward

Jenkinsfile
----
#
Make jenkins choose stage before clone code into each agent
No
No
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/156)
=> Add: choose stage outside agent

package.json, src/pages/Bounty/mybounty.js, src/pages/Bounty/reducer.js
fix mybounty getdata query after back btn
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/157)
=> fix mybounty getdata query after back btn

src/components/PageFoot/index.js
fix footer position
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/159)
=> fix footer position

src/components/PageFoot/index.js
modify footer align
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/160)
=> modify footer align

src/lang/zh.js, src/pages/Solution/action.js, src/pages/Solution/editsolution.js, src/pages/Solution/reducer.js
add submission confirm dialog
bugfix
no
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/161)
=> add submission confirm dialog

src/components/PageFoot/index.js
fix link to faqs page
bugfix
no
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/164)
=> fix link to faqs page

src/components/Input/index.js, src/components/SignInVia/index.js, src/constants.js, src/lang/en.js, src/lang/zh.js, src/pages/BindAccount/index.js, src/pages/SignUp/index.js, src/pages/UserInfo/settings.js, src/route/router.js, src/utils/api.js, src/utils/index.js
feature Wechat login
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/166)
=> feature Wechat login

src/lang/zh.js, src/pages/BindAccount/index.js, src/pages/UserInfo/settings.js
fix email modal submit, hide wechat bind modal in mobile
bugfix
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/168)
=> fix email modal submit, hide wechat bind modal in mobile

src/pages/SignUp/index.js, src/utils/api.js, src/utils/index.js
fix show recaptcha err duplicate
bugfix
no
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/170)
=> fix show recaptcha err duplicate

src/components/Tooltip/index.js, src/lang/en.js, src/lang/zh.js, src/pages/UserInfo/withdraw.js
add withdraw limit tips
no
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/165)
=> add withdraw limit tips

src/lang/en.js, src/lang/zh.js, src/pages/UserInfo/withdraw.js
feature
no
no
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/173)
=> wallet url and address placeholder

src/components/PageFoot/index.js
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/177)
=> change copyright

src/lang/en.js, src/lang/zh.js
update fc txt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/179)
=> update fc txt

src/components/PageFoot/index.js, src/lang/en.js, src/lang/zh.js
fc txt update
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/180)
=> fc txt update

oss-utils/index.js, package.json, src/constants.js, src/utils/api.js, src/utils/index.js, yarn.lock
Server sign upload
feature
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/181)
=> Server sign upload

src/index.js
update sentry cfg
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-bounty/184)
=> update sentry cfg

src/pages/UserInfo/withdraw.js, webpack.dev.config.js
=> feat: add Cobo

src/pages/UserInfo/withdraw.js
=> feat: fix style

src/lang/en.js, src/lang/zh.js, src/pages/UserInfo/action.js, src/pages/UserInfo/withdraw.js, webpack.dev.config.js
=> feat: withdraw address

Jenkinsfile
---
ci changes
- use jenkins nodejs provider
- change the prod machine
yes
no
we need to change the dns resolver to the new prod machine
=> ci: use jenkins's nodejs plugin

src/pages/UserInfo/withdraw.js
=> feat: replace wallet with moonswap

src/components/PageFoot/index.js
=> feat: update copyright

src/components/PageFoot/index.js
=> feat: update pc copyright

src/constants.js
=> feat: recapcha key

src/pages/UserInfo/action.js, src/pages/UserInfo/withdraw.js, webpack.dev.config.js
=> feat: remove the limit of 50

src/components/PageFoot/index.js, src/constants.js, src/pages/UserInfo/action.js, src/pages/UserInfo/withdraw.js, webpack.dev.config.js
=> feat: remove fc limit

src/constants.js
=> feat: modify recaptcha key
